### ISSUE TITLE
Not move files to trash

### ISSUE THREAD

**Issue by iluuu1994** [pornel/ImageOptim#37]
I don't like that the original files are just moved to the trash.

Presenting all the optimised files, and then replacing them yourself would be better in some cases. Therefore you could add a button at the end of the process saying "Replace with original files". 

Or something like that.

**Comment by iluuu1994** [comment]
This is an old issue but still relevant.

Well, you could copy the images to a temp folder and process them there. You're currently showing each file and the savings in size which is great. So you could just add a button to the far right of the table view saying something like "Replace".

And at the bottom of the window (left to the "Again" button) you could add a "Replace all" button.

Thanks for this great and free and open source app! (since I was so grumpy in the original issue)

**Comment by pornel** [comment]
I don't think Replace button fits ImageOptim's UI (explained in https://github.com/pornel/ImageOptim/issues/37#issuecomment-30071307)

The compression is kept lossless and idempotent specifically so that you don't need to inspect the files and they can be safely saved.

And now ImageOptim has a "Revert" option, so if you decide you didn't want some files optimized you can restore originals from trash instantly.

**Comment by iluuu1994** [comment]
Fair enough ;)

**Comment by eugenesvk** [comment]
I know this is an old issue, but I think that the current behavior of silent deletes is a bit surprising to make it stand as is.

While the **risk of data loss** is already mentioned above, I'd like to add that the "revert" solution doesn't fully address it since our poor user can simply lack **any awareness** that data is destroyed since there is no UI indication
  - whether metadata is stripped (which the user might've configured for some old job) or
  - the conversion is lossy

Given that @kornelski insists on the extreme UI simplicity (https://github.com/ImageOptim/ImageOptim/issues/37#issuecomment-30071307) and doesn't want to add any buttons may I at least suggest adding two indicators to the status bar:
  - red/reddish `meta` or `strip meta` text if "Strip metadata..." option is enabled (I think it fine to show if either PNG or JPEG is enabled, but maybe an additional png/jpeg icon indicator is warranted)
    (another alternative to this would be a column that shows for which files metadata was stripped to allow to revert if that wasn't users intention, but this might be worse since it requires inspecting a potentially very long list and is only know after the fact)
   - likewise a `lossy` text or some icon indicator is "Enable lossy minification" is enabled

Ideally these two options could be changed by clicking the status bar indicators (so red `meta` would become grey `meta`) or having a toolbar, but just showing the information to the user is already a big step forward

Hopefully you'd consider some of these data loss risk mitigation options which improve upon the "revert" solution and thanks for this otherwise great and simple app
