### ISSUE TITLE
Compress JPEGs at less than 80% quality

### ISSUE THREAD

**Issue by samjewell** [pornel/ImageOptim#73]
Loving ImageOptim, thanks so much...

Would love it even more however if there was an option to compress JPEGs at quality levels lower than 80% - currently 80% is the minimum quality level you are allowed.

**Comment by jaydenseric** [comment]
This is really killing me. I need to take images to potato town because we are displaying them at half size in the browser anyway.

I develop big campaign websites and fully support Retina. Our rotator sequences in particular I need to dial right down: [http://firstevermazdacx-3.com.au/#/section/exterior](http://firstevermazdacx-3.com.au/#/section/exterior).

Almost any JPG optimization is lossy, noticeable at the currently supported 80% level anyway. The quality slider is buried in options, where you can only change the setting deliberately and knowingly.

> I can't do that without a proper UI for lossy optimizations.

Nothing wrong with the current UI, please just increase the range with at least a 50% minimum. Almost no development required, right? I'm begging.

**Comment by pathawks** [comment]
> Almost no development required, right?

Hey, it’s open source! *You* can do this for your self if you need it so badly and it would require no development.

**Comment by jaydenseric** [comment]
@pathawks This is a modification other users have been asking for for years, see #39. If I submitted a working pull request right now, my understanding is it would be rejected. I don't want to maintain a custom fork on my machine as that would not be a sustainable solution for our team or help the wider community. I blog and write guides and would love to be able to recommend this app for situations where greater optimisation is required.

**Comment by pornel** [comment]
If you want to deliberately lower quality then try https://imageoptim.com/mozjpeg

**Comment by jaydenseric** [comment]
Thanks for the link @pornel, love your work. Unfortunately this is not a perfect solution for us because:

1. We need very specific control over quality level, three levels is not granular enough.
2. We need to bulk optimise sets up to 100MB with trial-and-error adjustment, the internet in Australia is not really fast enough.
3. I trust you don't retain or cache images, but we prepare campaigns for big product launches and have to maintain pretty strict control over the media.

**Comment by pornel** [comment]
@jaydenseric In that case I'm afraid ImageOptim is not the right option for you. Try JpegMini or imgmin.
