### ISSUE TITLE
advpng 1.19

### ISSUE THREAD

**Issue by Jellyfrog** [pornel/ImageOptim#84]
There is a lot newer version of advpng; http://sourceforge.net/projects/advancemame/files/advancecomp/1.19/

Some stuff that might be of interest since 1.15:
```
* Changed to GPL3.
* Added zopfli support. It's enabled using -4, --shrink-insane.
* You can control the number of iterations with the new -i, --iter option.
* Added a new -k, --keep-file-time option to advzip [Marco Banfi].
```

**Comment by pornel** [comment]
I know, but ImageOptim has its own zopfli tool (with customisation to handle large files better), so these features are not useful in ImageOptim. 

Old advpng is useful for having an old 7zip build :)

**Comment by Jellyfrog** [comment]
Well there was a couple of bugfixes and other stuff, is it the same story with the rest of the programs? gifsicle and so on

**Comment by pornel** [comment]
It's different:

* optipng — I'm stuck with 0.6, because I wrote dirty alpha clearing patch for it. The patch needs to be rewritten for 0.7.
* jpegtran — I should switch to mozjpeg, although jpegrescan is sometimes still a little bit more efficient.
* gifsicle — I'm waiting for the upstream to merge lossy patch, otherwise I'll switch to my fork
* pngcrush — up to date
* pngout — up to date
* zopfli — I've merged upstream changes recently, so should be up to date

**Comment by Jellyfrog** [comment]
Then it was a lot more up to date than it might look! Version numbers confuses sometimes :)

**Comment by ace-dent** [comment]
There was a consensus that the 'legacy' version v1.15/1.16 of ADVCOMP, benefitted *some* png images due to the older version of 7zip and more extensive trials of 7zip.

However, in all my testing I cannot find a single image that is better compressed with the legacy version -vs- the newer 2.4 version (avoiding zopfli mode for a fair comparison). 
e.g. 
`for /L %%i in (1,1,4) do advdefLEGACY.exe -z%%i "%~1"` -vs- `for /L %%i in (1,1,3) do advdefNEW.exe -z%%i -i200 "%~1"`

Does anyone in the community have a counter example?
Is there an image which compresses better with the old 7zip code?
Is it that libdeflate (in v2.4) is equal to or better than 7zip?
